In [1]:
import sys
sys.path.append("../source")

In [2]:
import numpy as np
import math
import matplotlib.pyplot as plt
import pylab
from tqdm import trange
import scipy
import scipy.stats as stats
from scipy.stats import bernoulli
import matplotlib as mp
from numba import njit
from project_lib import *
import pandas as pd

In [16]:
def init_unif_distrib_consensus_data(unif_distib_consensus_data, experiment, N, R):
    if not ((unif_distib_consensus_data['N'] == N) 
            & (unif_distib_consensus_data['eps'] == round(R,2))
            ).any():
        unif_distib_consensus_data.at[experiment, "N"] = N
        unif_distib_consensus_data.at[experiment, "eps"] = R
        unif_distib_consensus_data.at[experiment, "consensus_x"] = 0
        unif_distib_consensus_data.at[experiment, "consensus_y"] = 0
        unif_distib_consensus_data.at[experiment, "consensus_probabity"] =0
        unif_distib_consensus_data.at[experiment, "simulation_time"] =0
        unif_distib_consensus_data.at[experiment, "simulation_count"] = 0

def update_unif_distrib_consensus_data(unif_distib_consensus_data, experiment, res_arr_fast):
    unif_distib_consensus_data.at[experiment, "consensus_x"] += res_arr_fast[-1, 0, 0]
    unif_distib_consensus_data.at[experiment, "consensus_y"] += res_arr_fast[-1, 0, 1]
    unif_distib_consensus_data.at[experiment, "consensus_probabity"] +=1
    unif_distib_consensus_data.at[experiment, "simulation_time"] +=res_arr_fast.shape[0]
    


dtypes = {
    'N': np.int64,
    'eps': np.float64,
    'consensus_x': np.float64,
    'consensus_y': np.float64,
    'consensus_probabity': np.float64,
    'simulation_time': np.int64,
    'simulation_count': np.int64
}

In [18]:
unif_distib_consensus_data = pd.DataFrame(columns=["N", "eps", "consensus_x", "consensus_y","consensus_probabity", "simulation_time", "simulation_count"], dtype=object)
# unif_distib_consensus_data.to_csv('unif_distib_consensus_data.csv',sep=";", index=False)
unif_distib_consensus_data

Empty DataFrame
Columns: [N, eps, consensus_x, consensus_y, consensus_probabity, simulation_time, simulation_count]
Index: []

In [19]:
unif_dtypes = {
    'N': np.int64,
    'eps': np.float64,
    'consensus_x': np.float64,
    'consensus_y': np.float64,
    'consensus_probabity': np.float64,
    'simulation_time': np.int64,
    'simulation_count': np.int64
}
unif_distib_consensus_data = pd.read_csv('unif_distib_consensus_data.csv', sep=";", dtype=unif_dtypes)
unif_distib_consensus_data

,N,eps,consensus_x,consensus_y,consensus_probabity,simulation_time,simulation_count
0,50,0.15,0.000000,0.000000,0.0,0,200
1,50,0.20,0.000000,0.000000,0.0,0,200
2,50,0.25,0.522432,0.459108,1.0,10,200
3,50,0.30,28.444537,28.194056,56.0,514,200
4,50,0.35,77.673857,78.457409,155.0,1053,200
5,50,0.40,100.175477,98.959998,199.0,1045,200
6,50,0.45,99.545035,100.092801,200.0,871,200
7,50,0.50,100.553961,100.384974,200.0,803,200
8,50,0.55,99.837694,99.178135,200.0,795,200
9,50,0.60,99.623504,98.789098,200.0,724,200
10,50,0.65,100.297921,100.012020,200.0,609,200
11,50,0.70,101.343413,100.275264,200.0,600,200
12,50,0.75,100.144214,99.683307,200.0,600,200
13,50,0.80,99.327828,99.931477,200.0,600,200
14,50,0.85,99.737287,99.917876,200.0,600,200
15,50,0.90,99.590705,100.425984,200.0,600,200
16,50,0.95,100.000044,99.083123,200.0,600,200
17,50,1.00,99.686278,100.916380,200.0,600,200

In [6]:
R = 0.2  # радиус доверия
eps = 1e-4  # допустимая точность
n = 50  # количество агентов по одной оси
N = n

In [20]:
experiments = 400
R_array = [round(i,2)for i in np.arange(0.15, 1.01, 0.05)]
beta_params_array =  np.arange(0.5, 5.1, 0.5)
beta_params_array

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
unif_distib_consensus_data.to_csv('unif_distib_consensus_data.csv',sep=";", index=False)

In [11]:
func = create_round_conf_func

In [21]:
experiment = unif_distib_consensus_data.index[-1] +1

simulation_func = HK_2D_sim
count_consensus = 0
CONSENSUS_BORDER = 5
for R in R_array:
    confidence = func(R)
    init_unif_distrib_consensus_data(unif_distib_consensus_data, experiment, N, R)
    if count_consensus>=CONSENSUS_BORDER: simulation_func=HK_2D_sim
    print(f"N:{N} R:{R} func:{simulation_func.__name__} count:{count_consensus}")

    for i in trange(experiments):
        x0 = np.random.uniform(0,1,(N,2))
        res_arr_fast, check_fast = simulation_func(x0, confidence, R * 1e-3, 1000)
        if check_fast:
            cluster_of_agent, cluster_sizes = caln_n_clusters(res_arr_fast[-1, :, :], confidence)
            experiment = unif_distib_consensus_data[
                ((unif_distib_consensus_data['N'] == N) 
                    & (unif_distib_consensus_data['eps'] == round(R,2)))].index[0]
            unif_distib_consensus_data.at[experiment, "simulation_count"] +=1
            if len(cluster_sizes)==1:
                # we have consensus
                count_consensus+=1
                update_unif_distrib_consensus_data(unif_distib_consensus_data, experiment, res_arr_fast)
        else:
            draw_HK_2D_simulation(res_arr_fast, 'plasma')
    experiment = unif_distib_consensus_data.index[-1] +1
unif_distib_consensus_data

N:50 R:0.15 func:HK_2D_sim count:0

100%|██████████| 400/400 [00:01<00:00, 259.60it/s]

N:50 R:0.2 func:HK_2D_sim count:0

100%|██████████| 400/400 [00:01<00:00, 244.15it/s]

N:50 R:0.25 func:HK_2D_sim count:0

100%|██████████| 400/400 [00:01<00:00, 246.22it/s]

N:50 R:0.3 func:HK_2D_sim count:2

100%|██████████| 400/400 [00:01<00:00, 224.61it/s]

N:50 R:0.35 func:HK_2D_sim count:99

100%|██████████| 400/400 [00:01<00:00, 260.66it/s]

N:50 R:0.4 func:HK_2D_sim count:407

100%|██████████| 400/400 [00:01<00:00, 295.84it/s]

N:50 R:0.45 func:HK_2D_sim count:800

100%|██████████| 400/400 [00:01<00:00, 314.27it/s]

N:50 R:0.5 func:HK_2D_sim count:1200

100%|██████████| 400/400 [00:01<00:00, 330.07it/s]

N:50 R:0.55 func:HK_2D_sim count:1600

100%|██████████| 400/400 [00:01<00:00, 326.93it/s]

N:50 R:0.6 func:HK_2D_sim count:2000

100%|██████████| 400/400 [00:01<00:00, 297.68it/s]

N:50 R:0.65 func:HK_2D_sim count:2400

100%|██████████| 400/400 [00:01<00:00, 358.95it/s]

N:50 R:0.7 func:HK_2D_sim count:2800

100%|██████████| 400/400 [00:01<00:00, 362.20it/s]

N:50 R:0.75 func:HK_2D_sim count:3200

100%|██████████| 400/400 [00:01<00:00, 355.84it/s]

N:50 R:0.8 func:HK_2D_sim count:3600

100%|██████████| 400/400 [00:01<00:00, 373.01it/s]

N:50 R:0.85 func:HK_2D_sim count:4000

100%|██████████| 400/400 [00:01<00:00, 368.61it/s]

N:50 R:0.9 func:HK_2D_sim count:4400

100%|██████████| 400/400 [00:01<00:00, 317.47it/s]

N:50 R:0.95 func:HK_2D_sim count:4800

100%|██████████| 400/400 [00:01<00:00, 362.92it/s]

N:50 R:1.0 func:HK_2D_sim count:5200

100%|██████████| 400/400 [00:01<00:00, 362.19it/s]

,N,eps,consensus_x,consensus_y,consensus_probabity,simulation_time,simulation_count
0,50,0.15,0.000000,0.000000,0.0,0,600
1,50,0.20,0.000000,0.000000,0.0,0,600
2,50,0.25,1.560785,1.549373,3.0,29,600
3,50,0.30,76.412664,76.676250,153.0,1405,600
4,50,0.35,230.619802,232.336869,463.0,3168,600
5,50,0.40,296.008507,295.610820,592.0,3126,600
6,50,0.45,298.946249,300.795309,600.0,2620,600
7,50,0.50,299.733485,300.345382,600.0,2407,600
8,50,0.55,298.539095,298.927516,600.0,2391,600
9,50,0.60,299.636096,298.601446,600.0,2159,600
10,50,0.65,300.130675,298.314282,600.0,1848,600
11,50,0.70,301.454261,301.824426,600.0,1800,600
12,50,0.75,299.302665,297.968789,600.0,1800,600
13,50,0.80,299.810775,299.639359,600.0,1800,600
14,50,0.85,299.350106,301.644203,600.0,1800,600
15,50,0.90,298.706311,301.259397,600.0,1800,600
16,50,0.95,301.187433,299.415761,600.0,1800,600
17,50,1.00,298.600653,300.906610,600.0,1800,600

In [22]:
plt.figure(figsize=(10, 8))

cmap = mp.cm.get_cmap("plasma")
norm=plt.Normalize(vmin=0.15, vmax=5.5)
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)

# Plot lines for each beta value
df = data.query('N == @N')
plt.plot(df['eps'], df['consensus_probabity']/df['simulation_count'],  )

# Adding the HK_sample line (you'll need to adjust this based on your actual data)
plt.title(f' 2dHK Percentage of consensus N:{N}\n a,b - parameters beta distribution')
plt.xlabel('Eps')
plt.ylabel('Percentage')
plt.legend()
# Add a grid
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

C:\Users\Anastasia\AppData\Local\Temp\ipykernel_10204\1038572922.py:3: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = mp.cm.get_cmap("plasma")

NameError: name 'data' is not defined